zju_mocap:
  exp_name: base_config-1.zju_mocap.10-min
  iter: [2000]
  no_perturbed_nrm: [true]
  skin_net_encoding_type: ["meta_skin_net"]
  sdf_mlp_type: ["frequency_lipschitz"]
  non_rigid_offset_net_encoding_type: ["frequency_windowed"]
  non_rigid_offset_net_postional_encoding_anneal_steps: [5000]
  tfs_type: ["joint"]
  dmtet_grid: [128] #  [192, 256]
  tet_dir: tmp/quartet/meshes/
  batch: 2
  learning_rate_geometry: 0.0005
  learning_rate_material: 0.003
  learning_rate_motion: 0.0001
  learn_sdf_with_mlp: [true]
  use_texture_conditional_inputs: true
  learn_tet_vert_deform_with_mlp: false
  warmup_iter_tet: [100]
  learning_rate_final_mult: [1.0]
  # ks_max: ["'[0.0, 1.0, 1.0]'", "'[1.0, 1.0, 1.0]'"]
  texture_conditional_channel_idx: ["'[3]'"]
  use_training_tricks: [false]
  num_samples_per_bone: [50]
  vertices_laplace_regularizer: [0.0]
  tet_deform_regularizer: 0.0
  bone_sdf_regularizer: 0.0
  # albedo_regularizer: 0.0
  # ks_regularizer: 0.0
  # nrm_regularizer: 0.0
  # perturb_nrm_regularizer: 0.0
  # visibility_regularizer: 0.0
  light_regularizer: [0.005]
  sdf_regularizer: [0.02]
  enable_tet_vert_deform: true
  spp: [2]
  subdivide_aware_marching_tet: false
  sdf_mlp_lipschitz_regularizer: 1.0e-6 
  skin_net_lipschitz_regularizer: 1.0e-6
  prune_tetmesh_iters: "'[500]'"
  subdivide_tetmesh_iters: ["'[500]'"]
  learn_non_rigid_offset: true
  non_rigid_type: ['canon']
  non_rigid_offset_regularizer: [0.1]
  non_rigid_bone_offset_regularizer: [0.0]
  non_rigid_offset_net_lipschitz_regularizer: 1.0e-6
  mlp_texture_internal_dims: [64]
  split_non_rigid_offset_net_optim_steps: [500]
  dataset@_global_: [ zju_mocap/387.yaml, zju_mocap/390.yaml, zju_mocap/392.yaml, zju_mocap/393.yaml, zju_mocap/394.yaml]
  pre_load: false
  out_dir: outputs/\${exp_name}/zju_mocap/\${subject_id}/\${now:%y%m%d_%H%M%S}
  pre_train_with_smpl: true
  invisible_triangle_sdf_regularizer: 0.01
  use_vitruvian_pose: [true]
  skinning_regularizer: 0.0
  smpl_surface_skinning_regularizser: 10.0
  non_rigid_offset_laplace_regularizer: 20
  validate_interval: 2000
