defaults:
  - h36m/s9p.yaml@_here_
  - _self_


subject_id: 11

train_begin_frame_id: 0
train_num_frame: 200

# validate_begin_frame_id: 1000  # 200 * 5
# validate_num_frame: 13  # 82 / 6

validate_begin_frame_id_novel_view: 0
validate_num_frame_novel_view: 34  # ceil(200 / 6) = 33
validate_begin_frame_id_novel_pose: 1000  # 200 * 5
validate_num_frame_novel_pose: 14  # ceil(82 / 6) = 14