defaults:
  - h36m/s9p.yaml@_here_
  - _self_


subject_id: 5

train_begin_frame_id: 0
train_num_frame: 250

# validate_begin_frame_id: 1250  # 250 * 5
# validate_num_frame: 21  # 127 / 6

validate_begin_frame_id_novel_view: 0
validate_num_frame_novel_view: 42  # ceil(250 / 6) = 42
validate_begin_frame_id_novel_pose: 1250  # 250 * 5
validate_num_frame_novel_pose: 22  # ceil(127 / 6) = 21
