defaults:
  - zju_mocap-easymocap/313.yaml@_here_
  - _self_

subject_id: 315

train_begin_frame_id: 0
train_num_frame: 400

validate_views: [1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 19, 20]  # 313 & 315 only have 21 views, instead of 23 view
# validate_begin_frame_id: 400
# validate_num_frame: 1000

validate_begin_frame_id_novel_view: 0
validate_num_frame_novel_view: 14  # ceil(400 / 30) = 14
validate_begin_frame_id_novel_pose: 400
validate_num_frame_novel_pose: 34  # ceil(1000 / 30) = 34